// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kasxqrndnmqlekitpmod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imthc3hxcm5kbm1xbGVraXRwbW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwODg3MzIsImV4cCI6MjA2NzY2NDczMn0.LFnZynh3-kJpIQo9EO5mJRbOTo9lPpUdiH-kwB3HZ0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});